TINY-3926: Fixed stylesheets not cleaned up when all editors are destroyed
tinymce/tinymce pull request #5984
Opened 2020-08-25 05:40 UTC by lnewson

Related Ticket: TINY-3926

Description of Changes:
* Cleans up stylesheets loaded via `StyleSheetLoader` or `editor.dom.loadCss()` when all editors using the related stylesheets have been removed. This uses a counter to determine how many times the stylesheet has been loaded and then decrements the counter on unload calls. If the loader believes nothing is using it, then it'll remove the stylesheet from the DOM.
* This also cleans up the `loadCss` API to use the `StyleSheetLoader` to remove duplicate code. It should functionally be identical.

Note: Added Tyler as there's new APIs here, so need to check the API jsdoc strings.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/` for new features (if applicable)
* [x] License headers added on new files (if applicable)

Review:
* [x] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

2020-08-25 05:45 UTC, lnewson commented on modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
>   * For commercial licenses see https://www.tiny.cloud/
I've removed a lot of old legacy code here from Firefox 9 and less, etc... here, as it just bloated the code and definitely wasn't useful.

Eg. The `load` event was added in Firefox 9 as per https://bugzilla.mozilla.org/show_bug.cgi?id=185236

2020-08-25 05:51 UTC, lnewson commented on modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
> +          if (owner && (owner as Element).id === link.id) {
This possibly should have a guard, however `id` will just be undefined if it's not an element so adding the guard would just end up in bloat which is why I opted for the cast here.

2020-08-25 09:03 UTC, lnewson commented on modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
> -    link.async = false;
Neither of these (async and defer) are valid properties for a link element. This wasn't picked up previously as the type was `any`.

2020-08-25 09:07 UTC, lnewson commented on modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
> +  unload: (url: string) => void;
Not attached to these names, so if anyone has a better suggestion let me know.

2020-08-26 07:13 UTC, ashfordneil approved these changes

2020-08-26 07:46 UTC, ltrouton approved these changes

2020-08-28 06:19 UTC, lnewson commented on modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
> +    link = linkElem.dom;
It mutates it in the `resolve` function to clean up the reference. That may not be needed anymore, but I'm not keen on removing that at this point in time.

2020-08-28 09:22 UTC, tylerkelly13 requested changes

2020-08-28 09:22 UTC, tylerkelly13 commented on modules/tinymce/src/core/main/ts/api/dom/StyleSheetLoader.ts
> +   * Unloads each specified CSS file if no resources currently depend on it.
s/file/files/

2020-08-28 09:24 UTC, tylerkelly13 approved these changes

2020-08-28 09:35 UTC, merged