TINY-6648: Expand types for entity encoding
tinymce/tinymce pull request #6209
Opened 2020-11-12 04:10 UTC by ashfordneil

Related Ticket: TINY-6648

Description of Changes:
* The entity_encoding setting type was incorrect, and overly restrictive. While it would be nice to fix this properly with TypeScript's new template types, for now I've just widened it to accept any string.

Pre-checks:
* [ ] Changelog entry added
* ~[ ] Tests have been added (if applicable)~
* ~[ ] Branch prefixed with `feature/` for new features (if applicable)~
* ~[ ] License headers added on new files (if applicable)~

Review:
* [x] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

2020-11-12 04:28 UTC, lnewson requested changes

2020-11-12 04:28 UTC, lnewson commented on modules/tinymce/src/core/main/ts/api/SettingsTypes.ts
> +export type EntityEncoding = 'named' | 'numeric' | 'raw' | string;
Adding `string` here just dwarfs the others and removes all type safety. We need to come up with a better solution here.

2020-11-12 04:45 UTC, lnewson approved these changes

2020-11-12 09:30 UTC, metricjs approved these changes

2020-11-12 09:30 UTC, metricjs commented on modules/tinymce/changelog.txt
> +    Fixed type signature for `entity_encoding` setting not accepting delimited lists #TINY-6648
```suggestion
    Fixed the type signature for the `entity_encoding` setting not accepting delimited lists #TINY-6648
```

2020-11-12 23:09 UTC, ltrouton approved these changes

2020-11-16 03:14 UTC, metricjs approved these changes

2020-11-16 03:44 UTC, merged