TINY-6738  Remove 'scope' parameter from Table RowDialog
tinymce/tinymce pull request #6463
Opened 2021-01-25 10:44 UTC by camiloHimura

Related Ticket:

Description of Changes:
* Unsupported attribute removed
* Pass test
![image](https://user-images.githubusercontent.com/6851052/105695684-a6ec2800-5f02-11eb-88ca-3121ccf04474.png)

Pre-checks:
* [ ] Changelog entry added
* [ ] Tests have been added (if applicable)
* [ ] Branch prefixed with `feature/` for new features (if applicable)
* [ ] License headers added on new files (if applicable)

Review:
* [ ] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

2021-01-25 11:27 UTC, lnewson approved these changes

2021-01-25 11:37 UTC, lnewson commented on modules/tinymce/changelog.txt
> +    Fixed Remove 'scope' parameter from table rows #TINY-6738
To clarify more, this should read as a single sentence, including the `Fixed` part of the sentence.

2021-01-25 13:17 UTC, HAFRMO approved these changes

2021-01-25 13:45 UTC, camiloHimura commented on modules/tinymce/changelog.txt
> +    Fixed Remove 'scope' parameter from table rows #TINY-6738
Removed

2021-01-25 22:25 UTC, JamesToohey requested changes
Could we also please remove these references to row `scope` in this test

https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/table/test/ts/browser/HelpersTest.ts#L169
https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/plugins/table/test/ts/browser/HelpersTest.ts#L179

2021-01-26 08:04 UTC, JamesToohey approved these changes

2021-01-28 08:38 UTC, merged