TINY-6649: Accept commas in URL detection
tinymce/tinymce pull request #6468
Opened 2021-01-27 13:23 UTC by vpyshnenko

Related Ticket:

Description of Changes:
* Placeholder text

Pre-checks:
* [ ] Changelog entry added
* [ ] Tests have been added (if applicable)
* [ ] Branch prefixed with `feature/` for new features (if applicable)
* [ ] License headers added on new files (if applicable)

Review:
* [ ] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

2021-01-28 00:55 UTC, lnewson approved these changes

2021-01-28 00:55 UTC, lnewson commented on modules/polaris/src/main/ts/ephox/polaris/api/Regexes.ts
> +(?:\/[-+~=%.,()\/\w]*)?
We should mention about this modification in the section above that lists changes from the original.

- [ ] Update modifications section above

2021-01-28 01:00 UTC, lnewson requested changes
Actually, upon testing this regex I found an issue with including a comma... it'll incorrectly be included in the following (the comma is part of the sentence, not the URL):
> See https://www.tiny.cloud/, for more information

So we need to take that into account and make sure the comma isn't the last character in the regex. Worth noting this also appears to be an issue if the URL is at the end of the sentence, such as:
> See https://www.tiny.cloud.

2021-01-30 10:48 UTC, vpyshnenko commented
Attempt to exclude trailing comma at the end of whole  Regexes.link() regexp  causes  Regexes.autolink tests to fail. Turns out autolink function augments link() regexp with the group of trailing symbols. Modification of  just the path group of link() regexp doesn't affect autolink tests and  at least eliminates trailing comma issue in URLs terminating with path component,  thus extending editor's ability from:
- first comma in path breaks URL
to:
- last comma in path breaks URL

2021-02-01 01:46 UTC, ashfordneil approved these changes

2021-02-01 08:25 UTC, lnewson approved these changes
Thanks for reworking this to prevent the issue where the trailing comma would be included.

2021-02-01 08:25 UTC, lnewson commented on modules/polaris/src/test/ts/atomic/api/RegexesTest.ts
> +  const onlyWithPathLinks = { // Ignore trailing comma and period in URL path
Can you please put a newline above this, just to break up the test cases please?

2021-02-02 09:57 UTC, merged