TINY-7167: Patch the flaky test, and leave a TODO for future investigations
tinymce/tinymce pull request #6617
Opened 2021-03-12 06:43 UTC by ashfordneil

Related Ticket: TINY-7167

Description of Changes:
* There was a messy test flake, that's going to need a bit more investigation
* It needs more investigation, but for now this is a workaround

Pre-checks:
* ~[ ] Changelog entry added~
* ~[ ] Tests have been added (if applicable)~
* ~[ ] Branch prefixed with `feature/` for new features (if applicable)~
* ~[ ] License headers added on new files (if applicable)~

Review:
* [ ] Milestone set
* [ ] Review comments resolved

GitHub issues (if applicable):

2021-03-14 23:52 UTC, lnewson approved these changes

2021-03-15 00:58 UTC, lnewson requested changes
Changing my approval as per discussion this morning. We want to be as safe as possible so we shouldn't be upgrading all these deps, only bedrock itself.

2021-03-15 00:59 UTC, JamesToohey approved these changes
- [x] Approving assuming we revert the dependency updates

2021-03-16 01:08 UTC, ltrouton approved these changes

2021-03-16 01:11 UTC, lnewson approved these changes

2021-03-16 04:01 UTC, merged