TINY-9342: More accurate background color detection.
tinymce/tinymce pull request #8283
Opened 2022-11-21 13:57 UTC by HAFRMO

Related Ticket: 

Description of Changes:
More accurate background color detection.

Pre-checks:
* [x] ~Changelog entry added~
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

2022-11-21 15:03 UTC, spocke requested changes

2022-11-21 15:03 UTC, spocke commented on modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts
> +    TinySelections.setSelection(editor, [ 0, 0, 0, 0 ], 0, [ 0, 0, 0, 0 ], 1, true);
Not sure it needs to be a expanded selection. Shorter code.

```suggestion
    TinySelections.setCursor(editor, [ 0, 0, 0, 0 ], 1, true);
```

2022-11-21 15:10 UTC, HAFRMO commented on modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
> +const climbTreeForValue = (node: SugarElement<Element>, key: string): string =>
I assumed that we would want to skip any fully transparent value, even if it's not `0, 0, 0, 0`. Doesn't matter if it's that or `255, 255, 255, 0`, it's all 'unset' to us anyway.

I set it as a more generic function one to try and leave us with more options, but if you think it's too unclear I'll change it to be background only.

2022-11-21 15:13 UTC, spocke commented on modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
> +const climbTreeForValue = (node: SugarElement<Element>, key: string): string =>
Sure then use the parser from acid instead and see if the alpha value is 0. `RgbaColor.fromString(value).exists((c) => c.alpha !== 0)` or something.

2022-11-21 15:14 UTC, spocke commented on modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
> +const climbTreeForValue = (node: SugarElement<Element>, key: string): string =>
So somthing like:

```
const getClosestCssBackgroundColorValue = (scope: SugarElement<Element>): string => {
  const defaultBackgroundColor = 'rgba(0, 0, 0, 0)';
  const isValidColor = RgbaColor.fromString(value).exists((c) => c.alpha !== 0);
  return TransformFind.closest(scope, (node) => {
    if (SugarNode.isElement(node)) {
      const color = Css.get(node, key);
      return Optionals.someIf(isValidColor(color), color);
    } else {
      return Optional.none();
    }
  }).getOr(defaultBackgroundColor);
};
```

2022-11-22 06:25 UTC, spocke approved these changes

2022-11-22 06:27 UTC, spocke commented on modules/tinymce/src/themes/silver/main/ts/ui/core/color/ColorSwatch.ts
> +*/
```suggestion
// Climb up the tree to find the value of the background until finding a non-transparent value or defaulting.
```

2022-11-29 09:18 UTC, merged