TINY-9497: Enabled icon colors
tinymce/tinymce pull request #8417
Opened 2023-02-01 10:27 UTC by HAFRMO

Related Ticket: 

Description of Changes:
Icons did not have the ability to get colors, so added that. Same mechanism as toolbar buttons. Also exposed the getUiRoot function in test framework, as it can often be used.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

2023-02-01 11:21 UTC, spocke approved these changes

2023-02-01 11:21 UTC, spocke commented on modules/bridge/CHANGELOG.md
> +- Added new `setIconColor`-function to `nestedmenuitemspec`. #TINY-9497
```suggestion
- Added new `setIconFill`-function to `nestedmenuitemspec`. #TINY-9497
```

2023-02-01 11:21 UTC, spocke commented on modules/tinymce/src/themes/silver/main/ts/ui/menus/item/build/NestedMenuItem.ts
> +      SelectorFind.descendant(component.element, 'svg path[id="' + id + '"], rect[id="' + id + '"]').each((underlinePath) => {
```suggestion
      SelectorFind.descendant(component.element, `svg path[id="${id}"], rect[id="${id}"]`).each((underlinePath) => {
```

2023-02-01 11:21 UTC, spocke commented on modules/tinymce/CHANGELOG.md
> +- The foreground and background menu icons would not properly update to display the last used color. #TINY-9497
You also introduced a new `setIconFill` api to all nested menu items so a separate line for that would be nice.

2023-02-02 05:04 UTC, HAFRMO commented on modules/bridge/CHANGELOG.md
> +- Added new `setIconColor`-function to `nestedmenuitemspec`. #TINY-9497
Woups.

2023-02-03 06:25 UTC, spocke approved these changes

2023-02-03 06:25 UTC, spocke commented on modules/tinymce/CHANGELOG.md
> +- Added new `setIconFill` function to `nestedmenuitemspec` #TINY-9497
```suggestion
- Added new `setIconFill` function to `NestedMenuItemInstanceApi`. #TINY-9497
```
or
```suggestion
- Added new `setIconFill` API to nested menu items. #TINY-9497
```

2023-02-03 07:12 UTC, HAFRMO commented on modules/tinymce/CHANGELOG.md
> +- Added new `setIconFill` function to `nestedmenuitemspec` #TINY-9497
Fair enough.

2023-02-03 10:53 UTC, vpyshnenko approved these changes

2023-02-03 10:53 UTC, vpyshnenko commented on modules/tinymce/src/themes/silver/test/ts/browser/skin/OxideColorSwatchMenuTest.ts
> +    UiFinder.pWaitFor('The color should be black in the icon', TinyUiActions.getUiRoot(editor), 'path[id="tox-icon-highlight-bg-color__color"][fill="#E03E2D"]');
```suggestion
    UiFinder.pWaitFor('The color should be red in the icon', TinyUiActions.getUiRoot(editor), 'path[id="tox-icon-highlight-bg-color__color"][fill="#E03E2D"]');
```

2023-02-06 10:17 UTC, TheSpyder requested changes
See comments in JIRA

2023-02-14 01:44 UTC, HAFRMO commented
JIRA issue solved.

2023-02-21 09:45 UTC, TheSpyder approved these changes

2023-02-22 00:49 UTC, merged