TINY-10011: Preserve empty CET from pruning
tinymce/tinymce pull request #8971
Opened 2023-08-10 13:12 UTC by vpyshnenko

Related Ticket: TINY-10011

Description of Changes:
* Placeholder text

Pre-checks:
* [ ] Changelog entry added
* [ ] Tests have been added (if applicable)
* [ ] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [ ] Milestone set
* [ ] Docs ticket created (if applicable)

GitHub issues (if applicable):

2023-08-11 08:34 UTC, Afraithe commented
Could this be a breaking change for customers? Might need to think this through, altho the original issue seems very much like a bug, it is essentially by design (editor removes empty elements). I guess you can argue if an element is really empty if it has style and contenteditable false attributes, and that is what this patch is checkin (attrib).

2023-08-14 06:07 UTC, spocke requested changes

2023-08-14 10:11 UTC, vpyshnenko commented on modules/tinymce/src/core/main/ts/util/Quirks.ts
> +      return SelectorExists.descendant(scope, '[contenteditable="true"]');
done

2023-08-14 10:43 UTC, spocke approved these changes

2023-08-17 02:16 UTC, TheSpyder approved these changes

2023-08-17 06:00 UTC, merged