TINY-10275: Replace agar RealClipboard.sImportToClipboard with Clipboard.pPasteUrlItems
tinymce/tinymce pull request #9124
Opened 2023-10-30 14:39 UTC by spocke

Related Ticket: TINY-10275

Description of Changes:
* Removed the `RealClipboard.sImportToClipboard` API that uses wink that is problematic for bedrock selenium grid.
* Added new `Clipboard.pPasteUrlItems` to paste URL files as clipboard data items.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

2023-10-30 18:47 UTC, lorenzo-pomili requested changes
Fix `assertFileItem` and `assertFileItem` calls (they should wait for the result).

Edit: same for: `assertStringItem`

2023-10-30 18:47 UTC, lorenzo-pomili commented on modules/agar/src/test/ts/browser/api/ClipboardTest.ts
> +      createFileFromString('a.html', 123, '<b>Hello world!</b>', 'text/html')
changing the text doesn't break the test for example changing in:
```
createFileFromString('a.txt', 123, 'Hello world3!', 'text/plain'),
createFileFromString('a.html', 123, '<b>Hello world4!</b>', 'text/html')
```
results in a success even if the assertion also contains the specific `data`

2023-10-30 18:47 UTC, lorenzo-pomili commented on modules/agar/src/test/ts/browser/api/ClipboardTest.ts
> +      createFileFromString('a.html', 123, '<b>Hello world!</b>', 'text/html')
changing the expectation also make it pass so I think the problem is in the checker

2023-10-30 18:47 UTC, lorenzo-pomili commented on modules/agar/src/test/ts/browser/api/ClipboardTest.ts
> +      dataTransfer.items.add(createFileFromString('a.txt', 123, 'Hello world!', 'text/plain'));
same problem as above change the `text` doesn't make the test fail (the line below this works as expected)

2023-10-30 18:47 UTC, lorenzo-pomili commented on modules/agar/src/test/ts/browser/api/ClipboardTest.ts
> +    assertFileItem(dataTransfer.items[1], { type: 'text/plain', name: 'clipboard.txt', data: 'Hello world\n' });
same problem here these two line don't fail changing the data

2023-10-31 10:40 UTC, vpyshnenko approved these changes

2023-11-02 07:28 UTC, lorenzo-pomili approved these changes

2023-11-02 23:24 UTC, TheSpyder approved these changes

2023-11-02 23:24 UTC, TheSpyder commented on modules/agar/src/main/ts/ephox/agar/api/Clipboard.ts
> +    if (resp.status >= 400) {
```suggestion
    if (!resp.ok) {
```

2023-11-02 23:24 UTC, TheSpyder commented on modules/agar/src/main/ts/ephox/agar/api/Clipboard.ts
> +    const mime = blob.type.split(';')[0]; // Only grab mime type not charset encoding
Won't this all fail if the response isn't valid?

2023-11-02 23:24 UTC, TheSpyder commented on modules/agar/src/main/ts/ephox/agar/file/BlobReader.ts
Might be nice to combine this with the existing one somehow, but it's deep in a library and not exposed 🤔 

https://github.com/tinymce/tinymce/blob/66328ac1af232defe657d2c5286a2a6175fec9dd/modules/jax/src/main/ts/ephox/jax/core/BlobReader.ts#L3-L10

2023-11-03 12:29 UTC, merged