TINY-10590: Tree dom structure could confuse block merge boundary det…
tinymce/tinymce pull request #9474
Opened 2024-03-08 13:12 UTC by HAFRMO

Related Ticket: https://ephocks.atlassian.net/browse/TINY-10590

Description of Changes:
We incorrectly detected the placement of a cursor inside a div but outside a block to be a merge between two blocks ( the parent block and the contained block. This would result in incorrect behavior.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

2024-03-11 06:36 UTC, vpyshnenko approved these changes

2024-03-13 14:36 UTC, spocke requested changes

2024-03-13 14:36 UTC, spocke commented on modules/tinymce/src/core/test/ts/browser/delete/BlockMergeBoundaryTest.ts
> +    it('TINY-10590: If the cursor is between an internal block and a text-node it should not count as a block boundary', () => {
Flush this out with more tests. Like backspace on: `<div>A<p>|B</p>C</div>` or delete on `<div>A<p>B|</p>C</div>` so the bug is more wide that just this case. So think the `isNotAncestorial` will need to be expanded a bit to handle the other cases here.

2024-03-13 14:37 UTC, spocke commented on modules/tinymce/src/core/test/ts/browser/delete/BlockMergeBoundaryTest.ts
> +    it('TINY-10590: If the cursor is between an internal block and a text-node it should not count as a block boundary', () => {
I think you could use `Compare.contains` here so if from contains to or to contains from then it should not do anything.

2024-03-27 07:36 UTC, spocke approved these changes

2024-03-28 03:55 UTC, merged