TINY-10799: Color picker input field error tooltip.
tinymce/tinymce pull request #9707
Opened 2024-06-17 07:22 UTC by HAFRMO

Related Ticket: https://ephocks.atlassian.net/browse/TINY-10799

Description of Changes:
Add an error tooltip and error icon when the text input is not valid.

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

2024-06-18 04:45 UTC, TheSpyder requested changes
I posted the details in JIRA for wider comment, but we can't go inventing new error messaging. The editor-wide system for doing this is the `alertbanner` dialog component.

2024-06-18 08:01 UTC, spocke approved these changes

2024-06-19 05:57 UTC, HAFRMO commented on modules/oxide/src/less/theme/components/color-picker/color-picker.less
> +    border: 1px solid #f00;
Maybe? We didn't really establish what colors these should be. I can move them to some variables though. Should I keep it in color-picker.less or somewhere else?

2024-06-19 06:00 UTC, HAFRMO commented on modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
> +  'colorcustom.rgb.invalid': 'Numbers only, 0 to 255',
Do we have any notion-page or wider issue for this, or should I just make one specifically for this?

2024-07-01 14:00 UTC, HAFRMO commented on modules/tinymce/src/themes/silver/main/ts/ui/dialog/ColorPicker.ts
> +  'colorcustom.rgb.invalid': 'Numbers only, 0 to 255',
Added a ticket.

2024-07-03 10:27 UTC, ztomaszyk approved these changes
It would be good to write some tests to verify the icon is showing on incorrect value

2024-07-03 15:26 UTC, merged