TINY-11159: focus image dialog after closing an error alert
tinymce/tinymce pull request #9846
Opened 2024-08-29 08:04 UTC by ztomaszyk

Related Ticket: TINY-11159

Description of Changes:
* Placeholder text

Pre-checks:
* [ ] Changelog entry added
* [ ] Tests have been added (if applicable)
* [ ] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [ ] Milestone set
* [ ] ~~Docs ticket created (if applicable)~~

GitHub issues (if applicable):

2024-08-30 08:16 UTC, TheSpyder requested changes
This is a nice idea, but I think it crosses the public API boundary too much.

I would instead treat it as a bug; if there is an open modal dialog the `editor.windowManager.alert()` API should return focus to it automatically.

2024-08-30 08:16 UTC, TheSpyder commented on modules/tinymce/src/themes/silver/main/ts/ui/window/SilverDialogInstanceApi.ts
> +    focusSelf,
ooh, hang on. This is adding a public API, which has implications including documentation.

@spocke should we discuss this?

2024-08-30 11:12 UTC, spocke commented
> This is a nice idea, but I think it crosses the public API boundary too much.
> 
> I would instead treat it as a bug; if there is an open modal dialog the `editor.windowManager.alert()` API should return focus to it automatically.

I'm already on it we have a new approach where we will make the dropzone focusable like the other fields. We could put this back to draft in the meantime. I also don't want us to add a new public api if we don't need to.

2024-09-04 15:47 UTC, ztomaszyk commented
The dropzone is now focusable. I marked it as ready for review.

2024-09-06 13:13 UTC, lorenzo-pomili approved these changes

2024-09-10 08:12 UTC, spocke approved these changes

2024-09-10 16:11 UTC, ztomaszyk commented on modules/tinymce/src/plugins/image/test/ts/browser/UploadTabTest.ts
> +  it('TINY-: DialogFocusAfterErrorTest', async () => {
It was just a placeholder, forgot to change that 🤦‍♀️ Fixed!

2024-09-13 10:49 UTC, merged