TINY-11342: Added slider and size input to context forms
tinymce/tinymce pull request #9919
Opened 2024-10-14 11:43 UTC by spocke

Related Ticket: TINY-11342

Description of Changes:
* Adds new `contextsliderform` uses a native slider see ticket for details why
* Adds new `contextsizeinputform`
* Adds new APIs to disable the input and get the input disabled state
* Adds support for adding buttons in front of the input as well as after the input in context forms similar to dialog buttons that have a `align` property
* Adds support for `type=range` input to alloy so that we can use native sliders
* Made a common size input module that both dialog and context toolbar uses

Note:
* This is not fully working in terms of a11y since all context forms are rendered inside a toolbar I don't think that is what what we should be doing since that breaks keyboard navigation if you try to tab between the size input form fields. But this is a stop gap PR so that we can move forward we can circle back and fix a11y later. Logged in TINY-11394

Pre-checks:
* [x] Changelog entry added
* [x] Tests have been added (if applicable)
* [x] Branch prefixed with `feature/`, `hotfix/` or `spike/`

Review:
* [x] Milestone set
* [x] Docs ticket created (if applicable)

GitHub issues (if applicable):

2024-10-16 11:23 UTC, lorenzo-pomili approved these changes

2024-10-16 11:29 UTC, spocke commented on modules/tinymce/src/themes/silver/test/ts/browser/editor/contextform/ContextFormTest.ts
> +  it('TBA: Launching context form does not work if the context toolbar launcher is disabled', async () => {
No you are right it not needed found another one in the file as well that was not needed. 👍

2024-10-17 06:18 UTC, lorenzo-pomili requested changes
I just notice a bug, pressing back in the size context form the toolbar get hidden too

2024-10-17 06:59 UTC, spocke commented
> I just notice a bug, pressing back in the size context form the toolbar get hidden too

That is just a bug in the demo I think the image is no longer focused/selected. Not sure how important that is to fix.

2024-10-17 07:19 UTC, TheSpyder approved these changes

2024-10-17 13:59 UTC, merged